create extension if not exists pgcrypto;

do $$ begin create type public.app_role as enum ('business_owner','support_admin','super_admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.appointment_status as enum ('agendado','confirmado','finalizado','nao_compareceu','cancelado'); exception when duplicate_object then null; end $$;

create table if not exists public.businesses (
 id uuid primary key default gen_random_uuid(), name text not null, slug text unique, owner_name text not null default '', whatsapp text,
 open_time time not null default '08:00', close_time time not null default '18:00', daily_capacity integer not null default 20 check(daily_capacity>0),
 trial_started_at timestamptz not null default now(), trial_ends_at timestamptz not null default (now()+interval '7 days'), created_at timestamptz not null default now()
);
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', avatar_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.memberships (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, business_id uuid not null references public.businesses(id) on delete cascade, role public.app_role not null default 'business_owner', created_at timestamptz not null default now(), unique(user_id,business_id));
create table if not exists public.services (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, price numeric(12,2) not null default 0 check(price>=0), duration_minutes integer not null default 30 check(duration_minutes>0), active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.professionals (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.customers (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, name text not null, whatsapp text, notes text, created_at timestamptz not null default now());
create table if not exists public.appointments (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, customer_id uuid not null references public.customers(id), service_id uuid not null references public.services(id), professional_id uuid references public.professionals(id), appointment_date date not null, start_time time not null, status public.appointment_status not null default 'agendado', final_value numeric(12,2) not null default 0 check(final_value>=0), completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.daily_capacity (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, capacity_date date not null, max_appointments integer not null, created_at timestamptz not null default now(), unique(business_id,capacity_date));
create table if not exists public.monthly_goals (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, year integer not null, month integer not null check(month between 1 and 12), target_value numeric(12,2) not null default 0 check(target_value>=0), created_at timestamptz not null default now(), unique(business_id,year,month));
create table if not exists public.transactions (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, appointment_id uuid references public.appointments(id), type text not null default 'receita', amount numeric(12,2) not null default 0, occurred_at timestamptz not null default now());
create table if not exists public.reports (id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade, report_date date not null, appointments_total integer not null default 0, attended_total integer not null default 0, cancelled_total integer not null default 0, no_show_total integer not null default 0, realized_revenue numeric(12,2) not null default 0, average_ticket numeric(12,2) not null default 0, created_at timestamptz not null default now(), unique(business_id,report_date));
create table if not exists public.subscriptions (id uuid primary key default gen_random_uuid(), business_id uuid not null unique references public.businesses(id) on delete cascade, plan text not null default 'trial', status text not null default 'trial', started_at timestamptz, next_billing_at timestamptz, provider text, provider_subscription_id text, created_at timestamptz not null default now());
create table if not exists public.payment_events (id uuid primary key default gen_random_uuid(), business_id uuid references public.businesses(id) on delete set null, provider text, event_type text, external_id text, payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), business_id uuid references public.businesses(id) on delete set null, user_id uuid references auth.users(id) on delete set null, action text not null, entity text, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index if not exists memberships_user_idx on public.memberships(user_id);
create index if not exists memberships_business_idx on public.memberships(business_id);
create index if not exists appointments_business_date_idx on public.appointments(business_id,appointment_date,start_time);
create index if not exists customers_business_idx on public.customers(business_id);
create index if not exists services_business_idx on public.services(business_id);
create index if not exists professionals_business_idx on public.professionals(business_id);

create or replace function public.is_member(p_business_id uuid) returns boolean language sql security definer set search_path='' as $$ select exists(select 1 from public.memberships m where m.user_id=auth.uid() and m.business_id=p_business_id); $$;
create or replace function public.has_role(p_role public.app_role) returns boolean language sql security definer set search_path='' as $$ select exists(select 1 from public.memberships m where m.user_id=auth.uid() and m.role=p_role); $$;
create or replace function public.create_business_onboarding(p_business_name text,p_owner_name text,p_whatsapp text default null,p_open_time time default '08:00',p_close_time time default '18:00',p_daily_capacity integer default 20) returns uuid language plpgsql security definer set search_path='' as $$ declare uid uuid:=auth.uid(); bid uuid; slug_base text; slug_final text; begin if uid is null then raise exception 'Não autenticado'; end if; if exists(select 1 from public.memberships where user_id=uid) then raise exception 'Este usuário já possui uma empresa'; end if; if trim(coalesce(p_business_name,''))='' then raise exception 'Informe o nome da empresa'; end if; slug_base:=lower(regexp_replace(trim(p_business_name),'[^a-zA-Z0-9]+','-','g')); slug_base:=trim(both '-' from slug_base); if slug_base='' then slug_base:='empresa'; end if; slug_final:=slug_base||'-'||substr(replace(gen_random_uuid()::text,'-',''),1,6); insert into public.businesses(name,slug,owner_name,whatsapp,open_time,close_time,daily_capacity) values(trim(p_business_name),slug_final,trim(p_owner_name),nullif(trim(coalesce(p_whatsapp,'')),''),p_open_time,p_close_time,greatest(1,p_daily_capacity)) returning id into bid; insert into public.profiles(id,full_name) values(uid,trim(p_owner_name)) on conflict(id) do update set full_name=excluded.full_name,updated_at=now(); insert into public.memberships(user_id,business_id,role) values(uid,bid,'business_owner'); insert into public.subscriptions(business_id,plan,status,started_at,next_billing_at) values(bid,'trial','trial',now(),now()+interval '7 days'); return bid; end; $$;

revoke all on function public.is_member(uuid) from public,anon; grant execute on function public.is_member(uuid) to authenticated;
revoke all on function public.has_role(public.app_role) from public,anon; grant execute on function public.has_role(public.app_role) to authenticated;
revoke all on function public.create_business_onboarding(text,text,text,time,time,integer) from public,anon; grant execute on function public.create_business_onboarding(text,text,text,time,time,integer) to authenticated;

alter table public.businesses enable row level security; alter table public.profiles enable row level security; alter table public.memberships enable row level security; alter table public.services enable row level security; alter table public.professionals enable row level security; alter table public.customers enable row level security; alter table public.appointments enable row level security; alter table public.daily_capacity enable row level security; alter table public.monthly_goals enable row level security; alter table public.transactions enable row level security; alter table public.reports enable row level security; alter table public.subscriptions enable row level security; alter table public.payment_events enable row level security; alter table public.audit_logs enable row level security;

drop policy if exists business_select on public.businesses; create policy business_select on public.businesses for select to authenticated using(public.is_member(id) or public.has_role('support_admin') or public.has_role('super_admin'));
drop policy if exists business_update on public.businesses; create policy business_update on public.businesses for update to authenticated using(public.is_member(id));
drop policy if exists profile_select on public.profiles; create policy profile_select on public.profiles for select to authenticated using(id=auth.uid() or public.has_role('support_admin') or public.has_role('super_admin'));
drop policy if exists profile_update on public.profiles; create policy profile_update on public.profiles for update to authenticated using(id=auth.uid());
drop policy if exists membership_select on public.memberships; create policy membership_select on public.memberships for select to authenticated using(user_id=auth.uid() or public.has_role('support_admin') or public.has_role('super_admin'));

do $$ declare t text; begin foreach t in array ARRAY['services','professionals','customers','appointments','daily_capacity','monthly_goals','transactions','reports','subscriptions','payment_events','audit_logs'] loop execute format('drop policy if exists tenant_select on public.%I',t); execute format('create policy tenant_select on public.%I for select to authenticated using(public.is_member(business_id) or public.has_role('support_admin') or public.has_role('super_admin'))',t); execute format('drop policy if exists tenant_insert on public.%I',t); execute format('create policy tenant_insert on public.%I for insert to authenticated with check(public.is_member(business_id))',t); execute format('drop policy if exists tenant_update on public.%I',t); execute format('create policy tenant_update on public.%I for update to authenticated using(public.is_member(business_id)) with check(public.is_member(business_id))',t); execute format('drop policy if exists tenant_delete on public.%I',t); execute format('create policy tenant_delete on public.%I for delete to authenticated using(public.is_member(business_id))',t); end loop; end $$;

drop policy if exists profile_insert on public.profiles; create policy profile_insert on public.profiles for insert to authenticated with check(id=auth.uid());
